### ISSUE TITLE
Community Tools release checklist

### ISSUE THREAD

**Issue by nsarrazin** [huggingface/chat-ui#1434]
## Features & bugs
- [x] Support unknown outputs with `octet-stream` https://github.com/huggingface/chat-ui/commit/5f5f47012b1590782694bd56f695e46e5401c103
- [x] Improve MIME type parsing with `file-type` https://github.com/huggingface/chat-ui/commit/475f384543d54281aef7d36e2a44dce771351fcc
- [x] let the user paste the URL to a space directly #1435 
- [x] filter URLs that are not from huggingface.co #1435 
- [x] desync issues in form? not sure cc @gary149 
- [x] Add a custom thumbnail for `/tools` page like we do for assistants: https://github.com/huggingface/chat-ui/blob/main/static/huggingchat/assistants-thumbnail.png

## Release workflow
- [x] Create demo with RAG tool: https://huggingface.co/spaces/nsarrazin/rag-tool-template
- [x] remove feature flags PR #1433 
- [x] Write blog on https://github.com/huggingface/blog/
- [x] create feedback thread on discussions 
- [x] merge blog https://github.com/huggingface/blog/pull/2342
- [x] Merge and deploy #1433
