### ISSUE TITLE
Public repository todo

### ISSUE THREAD

**Issue by Grsmto** [huggingface/chat-ui#178]
Prepare the repository to be made public:
- [x] scan the repo for secrets? (I used gitleaks and seems ok)
- [ ] add "contribute" section to README
- [x] add banner/logo to README
- [x] add a license
- [x] add a description in the Github "About" section

**Comment by nsarrazin** [comment]
Closing this, since the repository has been public for a while :smile:
