### ISSUE TITLE
Release todo

### ISSUE THREAD

**Issue by gary149** [huggingface/chat-ui#3]
### To release

- [x] Mobile height (with Safari navigation bar it's overflowing)
- [x] Add social meta
- [x] Make "share" more visible
- [x] Code blocks screen overflow
- [x] Scrollbar adjustments for code blocks and navigation
- [x] Add disclaimer
- [x] Persistent conversations
- [x] Toggle for dark mode
- [ ] Models selector
- [x] use .prose class for assistant messages #16 
- [x] Share session with others
- [x] Errors handling
- [x] Auto-scroll #10
- [x] Retry with the same message?
- [ ] Handle max-tokens
- [x] Stop generating #86
- [x] Privacy modal
- [x] Icons
- [x] #12 

### Others
- [ ] Data export?
- [x] Auto-name conversations
- [ ] Expose and being able to configure model params
- [ ] Search conversations
- [ ] Like/dislikes responses
- [ ] Arrow up/down to browse user input history

**Comment by nsarrazin** [comment]
Can we close this now that we released ? @gary149

**Comment by gary149** [comment]
Yes, let's close it.
